### ISSUE TITLE
Support theme dynamic switch

### ISSUE THREAD

**Issue by oovm** [oovm/tailwind-rs#11]
```rust 
pub enum ThemeMode {
    Static,
    Dynamic,
    Custom(String)
}
```

### Static

```
.text-custom-200 {
    color: var(#FFFFFF)
}

.text-custom-300 {
    color: var(#FFFFFF)
}
```

### Dynamic

```scss
:root {
    --custom-200: #FFFFFF;
    --custom-300: #FFFFFF;
}

.text-custom-200 {
    color: var(--custom-200)
}

.text-custom-300 {
    color: var(--custom-300)
}
```

### Custom(String)

```scss
:root {
    <CUSTOM_STRING>
}

.text-custom-200 {
    color: var(--custom-200)
}

.text-custom-300 {
    color: var(--custom-300)
}
```
